name: CICD-TEST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: permission for gradle
      run: chmod +x ./gradlew
    - name: build and test with gradle
      run: ./gradlew build
    - name: run backend test
      run: ./gradlew test

  build-and-test-frontend:
    runs-on: ubuntu-latest
    needs: build-and-test-backend
    steps:
    - uses: actions/checkout@v2
    - name: setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'
    - name: install dependencies
      run: npm install
    - name: test cypress
      uses: actions/cache@v2
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
           ${{ runner.os }}-cypress-
    - name: run Cypress test
      run: npx cypress run
    - name: build frontend
      run: npm run dev

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test-backend, build-and-test-frontend]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to production
      run: echo "TEST"
