name: CICD-TEST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  
    - name: Set up JDK 21
      uses: actions/setup-java@v3  
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Change directory to backend
      run: cd backend
    - name: permissions for Gradle
      run: chmod +x ./gradlew
    - name: Run backend test
      run: ./gradlew test

  build-and-test-frontend:
    runs-on: ubuntu-latest
    needs: build-and-test-backend
    steps:
    - uses: actions/checkout@v3  
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 
    - name: Install dependencies
      run: npm install
    - name: Cache Cypress binary
      uses: actions/cache@v3  
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cypress-
    - name: Run Cypress test
      run: npx cypress run
    - name: Build frontend
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test-backend, build-and-test-frontend]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3 
    - name: Deploy to production
      run: echo "TEST"
